config/routes.rb
Rails.application.routes.draw do
  resources :cities
  resources :inventory_items
  resources :products
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "articles#index"
end

app/models/inventory_item.rb
require 'net/http'
require 'json'

class InventoryItem < ApplicationRecord
  attribute :weather
  belongs_to :product
  belongs_to :city
  validates :count, :presence => true,
    numericality: { greater_than_or_equal_to: 0 }
  validates_uniqueness_of :product_id, :scope => [:city_id]

  def location
    city.label
  end

  def weather
    begin
      request_url = "https://api.openweathermap.org/data/2.5/weather?lat=#{city.lat}&lon=#{city.long}&appid=#{ENV["OPENWEATHER_SECRET"]}"
      response = Rails.cache.fetch(request_url, :expires => 4.hour) do
          Net::HTTP.get_response(URI(request_url))
      end
      if response.code == "200"
        body = JSON.parse(response.body)
        body["weather"][0]["description"]
      else
        "Error: #{response.message}"
      end
    rescue =>e
      "Error: #{e.message}"
    end
  end
end

app/controllers/inventory_items_controller.rb
class InventoryItemsController < ApplicationController
  before_action :set_inventory_item, only: %i[ show edit update destroy ]

  # GET /inventory_items or /inventory_items.json
  def index
    @inventory_items = InventoryItem.all
  end

  # GET /inventory_items/1 or /inventory_items/1.json
  def show
  end

  # GET /inventory_items/new
  def new
    @inventory_item = InventoryItem.new
  end

  # GET /inventory_items/1/edit
  def edit
  end

  # POST /inventory_items or /inventory_items.json
  def create
    @inventory_item = InventoryItem.new(inventory_item_params)

    respond_to do |format|
      if @inventory_item.save
        format.html { redirect_to inventory_item_url(@inventory_item), notice: "Inventory item was successfully created." }
        format.json { render :show, status: :created, location: @inventory_item }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @inventory_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /inventory_items/1 or /inventory_items/1.json
  def update
    respond_to do |format|
      if @inventory_item.update(inventory_item_params)
        format.html { redirect_to inventory_item_url(@inventory_item), notice: "Inventory item was successfully updated." }
        format.json { render :show, status: :ok, location: @inventory_item }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @inventory_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /inventory_items/1 or /inventory_items/1.json
  def destroy
    @inventory_item.destroy

    respond_to do |format|
      format.html { redirect_to inventory_items_url, notice: "Inventory item was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_inventory_item
      @inventory_item = InventoryItem.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def inventory_item_params
      params.fetch(:inventory_item, {}).permit(:count, :product_id, :city_id)
    end
end

app/helpers/inventory_items_helper.rb
module InventoryItemsHelper
end

app/views/inventory_items/_form.html.erb
<%= form_with(model: inventory_item) do |form| %>
  <% if inventory_item.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(inventory_item.errors.count, "error") %> prohibited this inventory_item from being saved:</h2>

      <ul>
        <% inventory_item.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :product_id %><br>
    <%= form.collection_select :product_id, Product.order(:name),:id,:name_with_id %>
  </div>
  <div>
    <%= form.label :city_id %><br>
    <%= form.collection_select :city_id, City.order(:name),:id,:label %>
  </div>
  <div>
    <%= form.label :count %><br>
    <%= form.number_field :count %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/inventory_items/_inventory_item.html.erb
<tr id="<%= dom_id inventory_item %>">
    <td><%= inventory_item.id %></td>
    <td><%= inventory_item.product.id %></td>
    <td><%= inventory_item.product.name %></td>
    <td><%= inventory_item.product.description %></td>
    <% case @inventory_page %>
    <% when 'index' %>
        <td><%= inventory_item.count %></td>
        <td><%= inventory_item.location %></td>
        <td><%= inventory_item.weather %></td>
        <td>
            <%= link_to "Show Item", inventory_item %>
        </td>
    <% when 'show' %>
        <td><%= inventory_item.count %></td>
        <td><%= inventory_item.location %></td>
        <td><%= inventory_item.weather %></td>
    <% end %>
</tr>

app/views/inventory_items/edit.html.erb
<p><%= link_to "Back to Home", root_path %></p>

<h2>Editing Inventory Item</h2>

<%= render "form", inventory_item: @inventory_item %>

<br>

<div>
  <%= link_to "Show this inventory item", @inventory_item %> |
  <%= link_to "Back to inventory items", inventory_items_path %>
</div>

app/views/inventory_items/index.html.erb
<p style="color: green"><%= notice %></p>
<p><%= link_to "Back to Home", root_path %></p>

<h2>Inventory Items</h2>

<% @inventory_page = 'index' %>
<% if @inventory_items.size > 0 %>
    <table id="inventory_items">
        <tr>
            <th>ID</th>
            <th>Product ID</th>
            <th>Name</th>
            <th>Description</th>
            <th>Count</th>
            <th>Location</th>
            <th>Weather</th>
            <th>Actions</th>
        </tr>
        <% @inventory_items.order(:id).each do |inventory_item| %>
            <%= render inventory_item %>
        <% end %>
    </table>
<% else %>
    <p>There's no inventory items.</p>
<% end %>

<br>
<%= link_to "New inventory item", new_inventory_item_path %>

app/views/inventory_items/new.html.erb
<p><%= link_to "Back to Home", root_path %></p>

<h2>New Inventory Item</h2>

<%= render "form", inventory_item: @inventory_item %>

<br>

<div>
  <%= link_to "Back to inventory items", inventory_items_path %>
</div>

app/views/inventory_items/show.html.erb
<p style="color: green"><%= notice %></p>
<p><%= link_to "Back to Home", root_path %></p>

<% @inventory_page = 'show' %>
<table>
    <tr>
        <th>ID</th>
        <th>Product ID</th>
        <th>Name</th>
        <th>Description</th>
        <th>Count</th>
        <th>Location</th>
        <th>Weather</th>
    </tr>
    <%= render @inventory_item %>
</table>
<br>
<div>
  <%= link_to "Edit this inventory item", edit_inventory_item_path(@inventory_item) %> |
  <%= link_to "Back to inventory items", inventory_items_path %>

  <%= button_to "Destroy this inventory item", @inventory_item, method: :delete %>
</div>