config/routes.rb
Rails.application.routes.draw do
  resources :cities
  resources :inventory_items
  resources :products
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "articles#index"
end

app/models/city.rb
class City < ApplicationRecord
  belongs_to :country
  validates :name, :presence => true
  validates :lat, :presence => true
  validates :long, :presence => true
  validates_uniqueness_of :name, :scope => [:name, :country_id]

  def label
    if region.nil?
      "#{name}, #{country.name}"
    else
      "#{name}, #{region}, #{country.name}"
    end
  end
end

app/controllers/cities_controller.rb
require 'net/http'
require 'json'

class CitiesController < ApplicationController
  before_action :set_city, only: %i[ show edit update destroy ]

  # GET /cities or /cities.json
  def index
    @cities = City.all
  end

  # GET /cities/1 or /cities/1.json
  def show
  end

  # GET /cities/new
  def new
    @city = City.new
  end

  # GET /cities/1/edit
  def edit
  end

  # POST /cities or /cities.json
  def create
    formatted_params = lookup_city(city_params)
    if formatted_params[:error].present?
      @city = City.new
      render_error(formatted_params, :new)
    else
      @city = City.new(formatted_params)

      respond_to do |format|
        if @city.save
          format.html { redirect_to city_url(@city), notice: "City was successfully created." }
          format.json { render :show, status: :created, location: @city }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @city.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # PATCH/PUT /cities/1 or /cities/1.json
  def update
    formatted_params = lookup_city(city_params)
    if formatted_params[:error].present?
      render_error(formatted_params, :edit)
    else
      respond_to do |format|
        if @city.update(formatted_params)
          format.html { redirect_to city_url(@city), notice: "City was successfully updated." }
          format.json { render :show, status: :ok, location: @city }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @city.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # DELETE /cities/1 or /cities/1.json
  def destroy
    @city.destroy

    respond_to do |format|
      format.html { redirect_to cities_url, notice: "City was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_city
      @city = City.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def city_params
      values = params.fetch(:city, {}).permit(:name, :region, :country_id)
      if values[:region].is_a?(String) && values[:region].strip.size == 0
        values[:region] = nil
      end
      values
    end

    def lookup_city(params)
      name = params[:name]
      region = params[:region]
      country = Country.find(params[:country_id])
      location = if region.nil?
        "#{name},#{country.code}"
      else
        "#{name},#{region},#{country.code}"
      end

      request_url = "http://api.openweathermap.org/geo/1.0/direct?q=#{location}&limit=1&appid=#{ENV["OPENWEATHER_SECRET"]}"

      begin
        response = Rails.cache.fetch(request_url, :expires => 1.day) do
            Net::HTTP.get_response(URI(request_url))
        end
        if response.code == "200"
          body = JSON.parse(response.body)
          if body.size > 0 && body[0]["name"] == name
            city = body[0]
            {
              name: city["name"],
              region: city["state"],
              country: country,
              lat: city["lat"],
              long: city["lon"],
            }
          else
            { error: "There's no such city." }
          end
        else
          { error: response.message }
        end
      rescue =>e
        { error: e.message }
      end
    end

    def render_error(formatted_params, template)
      @city.errors.add(:name, :invalid, message: ": Error - #{formatted_params[:error]}")
      respond_to do |format|
        format.html { render template, status: :unprocessable_entity }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/views/cities/_city.html.erb
<tr id="<%= dom_id city %>">
    <td><%= city.id %></td>
    <td><%= city.name %></td>
    <td><%= city.region.nil? ? 'N/A': city.region %></td>
    <td><%= city.country.name %></td>
    <td><%= city.lat %></td>
    <td><%= city.long %></td>
    <% case @city_page %>
    <% when 'index' %>
        <td><%= link_to "Show this city", city %></td>
    <% end %>
</tr>

app/views/cities/_form.html.erb
<%= form_with(model: city) do |form| %>
  <% if city.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(city.errors.count, "error") %> prohibited this city from being saved:</h2>

      <ul>
        <% city.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </div>
  <div>
    <%= form.label :region %><br>
    <%= form.text_field :region %>
  </div>
  <div>
    <%= form.label :country_id %><br>
    <%= form.collection_select :country_id, Country.order(:name),:id,:name %>
  </div>
  <br>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/cities/edit.html.erb
<p><%= link_to "Back to Home", root_path %></p>

<h2>Editing City</h2>

<%= render "form", city: @city %>

<br>

<div>
  <%= link_to "Show this city", @city %> |
  <%= link_to "Back to cities", cities_path %>
</div>

app/views/cities/index.html.erb
<p style="color: green"><%= notice %></p>

<p><%= link_to "Back to Home", root_path %></p>

<h2>Cities</h2>

<% @city_page = 'index' %>
<% if @cities.size > 0 %>
    <table id="cities">
        <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Region</th>
            <th>Country</th>
            <th>Latitude</th>
            <th>Longitude</th>
            <th>Actions</th>
        </tr>
        <% @cities.each do |city| %>
            <%= render city %>
        <% end %>
    </table>
<% else %>
    <p>There's no inventory items.</p>
<% end %>
<br>
<%= link_to "New city", new_city_path %>

app/views/cities/new.html.erb
<p><%= link_to "Back to Home", root_path %></p>

<h2>New City</h2>

<%= render "form", city: @city %>

<br>

<div>
  <%= link_to "Back to cities", cities_path %>
</div>

app/views/cities/show.html.erb
<p style="color: green"><%= notice %></p>

<p><%= link_to "Back to Home", root_path %></p>

<table id="cities">
    <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Region</th>
        <th>Country</th>
        <th>Latitude</th>
        <th>Longitude</th>
    </tr>
    <%= render @city %>
</table>
<br>
<div>
  <%= link_to "Edit this city", edit_city_path(@city) %> |
  <%= link_to "Back to cities", cities_path %>

  <%= button_to "Destroy this city", @city, method: :delete %>
</div>